name: Build and test the server application
on:
  workflow_call:
    inputs:
      run_tests:
        description: "Whether to run tests or not"
        required: false
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Gradle
        run: ./gradlew buildDockerImageTarball

      #- name: Run tests
      #  if: ${{ github.event.inputs.run_tests }}
      #  run: ./gradlew test

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: cobol4j-aws-web:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
